broker:
  host: "localhost"
  port: 1883
  user: ""
  password: ""

cfg:
  pull_period_ms: 100
  changes_only: True
  status_period_sec: 10

true_list:
  - 1
  - True
  - true
  - On
  - on
  - "Set"
  - "set"

false_list:
  - 0
  - False
  - false
  - Off
  - off

convert_tables:
  - &bin_filter 
    - name: on_value
      broker: 1
      file: 1
      inv: 0
    - name: off_value
      broker: 0
      file: 0
      inv: 1      
    - broker: "*"
      file: null
    - broker: null
      file: "*"      
  - &bool_to_bin 
    - broker: "True"
      file: 1
    - broker: "False"
      file: 0
    - broker: "*"
      file: null
    - broker: null
      file: "*"

