broker:
  host: "localhost"
  port: 1883
  user: ""
  password: ""

cfg:
  pull_period_ms: 10000
  changes_only: True
  status_period_sec: 10

milur:
  topic: "Counters"
  port: "COM15"
  address:
    - 21
    - 23