

TEST_ADR = 0x17


GET_ID_CMD	=	1
SET_ID_CMD	=	2
nop_ID_CMD	=	3
nop_ID_CMD	=	4
LISTINIT_ID_CMD	=	5
GETLISTNE_ID_CMD	=	6
nop_ID_CMD	=	7
AOPEN_ID_CMD	=	8
ARELEASE_ID_CMD	=	9
SETRTC_ID_CMD	=	10
GET_EVTLIST_ID_CMD	=	11
GET_ENTALIST_ID_CMD	=	12
getPWIRecord_ID_CMD	=	13
PWILIST_SEARCH_ID_CMD	=	14
GETCURINDEX_ID_CMD	=	15
LIST_SEARCH_ID_CMD	=	16
GET_COLLECTION_ID_CMD	=	17
nop_ID_CMD	=	18
nop_ID_CMD	=	19
SET_IDM_SERVICE_ID_CMD	=	20
UPDATE_FIRMWARE_ID_CMD	=	21
SET_RTC_G3PLC_ID_CMD	=	22
GET_METERINFO_G3PLC_ID_CMD	=	23
nop_ID_CMD	=	24
nop_ID_CMD	=	25
nop_ID_CMD	=	26
nop_ID_CMD	=	27
nop_ID_CMD	=	28
nop_ID_CMD	=	29
SET_SOFT_RTC_CORRECTION_ID_CMD	=	30
SET_ROUND_RTC_TO_MINUTE_ID_CMD	=	31
SET_ROUND_RTC_TO_QUARTERHOUR_ID_CMD	=	32

FREQ_ID_DATA = 9
RATE_ID_DATA = 10
INDICATION_ID_DATA = 11
CTRL_FN_ID_DATA = 13
RTC_ID_DATA = 14
HOLIDAYS_ID_DATA = 15
PWI_ID_DATA = 16
EVENTS_ID_DATA = 17
ERR_LST_ID_DATA = 18
MAX_RATES_ID_DATA = 19

MODEL_ID_DATA = 32
FW_ID_DATA = 33
RTC_CALIBR_ID_DATA = 34
TIME_AUTO_SW_ID_DATA = 35

SN_ID_DATA = 68

UA_ID_DATA = 100






ACCESS_LVL_USER = 0
ACCESS_ADM_USER = 1
ACCESS_DEV_USER = 2

ACCESS_PWD_USER = [255]*6
